In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json

In [3]:
#initial directory
os.getcwd()
#creating an empty dataframe
df = pd.DataFrame()
os.chdir('D:\\programming\\practice\\Project')
cwd = os.getcwd()

In [5]:
# dataset file
os.chdir(cwd+'\Flight dataset')
lisofiles = os.listdir()
outerloop_reset = os.getcwd()
for i in lisofiles[:len(lisofiles)-1]:
    os.chdir(os.getcwd()+f'\\{i}')
    loopinit = os.getcwd()
    for i in os.listdir():
        print(i)
        temp = pd.DataFrame()
        os.chdir(os.getcwd()+f'\\{i}')
        print(os.getcwd())
        temp = pd.read_csv(os.listdir()[0],low_memory=False)
        df = pd.concat([temp,df])
        os.chdir(loopinit)
    os.chdir(outerloop_reset)

On_Time_On_Time_Performance_2016_1
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_1
On_Time_On_Time_Performance_2016_10
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_10
On_Time_On_Time_Performance_2016_11
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_11
On_Time_On_Time_Performance_2016_12
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_12
On_Time_On_Time_Performance_2016_2
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_2
On_Time_On_Time_Performance_2016_3
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_3
On_Time_On_Time_Performance_2016_4
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_4
On_Time_On_Time_Performance_2016_5
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_5
On_Time_On_Time_Performance_2016_6
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_6
On_Time_On_Time_Performance_2016_7
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_7
On_Time_On_Time_Performance_2016_8
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_8
On_Time_On_Time_Performance_2016_9
D:\programming\practice\Project\Flight dataset\2016\On_Time_On_Time_Performance_2016_9
On_Time_On_Time_Performance_2017_1
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_1
On_Time_On_Time_Performance_2017_10
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_10
On_Time_On_Time_Performance_2017_11
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_11
On_Time_On_Time_Performance_2017_12
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_12
On_Time_On_Time_Performance_2017_2
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_2
On_Time_On_Time_Performance_2017_3
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_3
On_Time_On_Time_Performance_2017_4
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_4
On_Time_On_Time_Performance_2017_5
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_5
On_Time_On_Time_Performance_2017_6
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_6
On_Time_On_Time_Performance_2017_7
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_7
On_Time_On_Time_Performance_2017_8
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_8
On_Time_On_Time_Performance_2017_9
D:\programming\practice\Project\Flight dataset\2017\On_Time_On_Time_Performance_2017_9

In [6]:
df1 = df
# df1.to_csv('./combine2016-2017')
df1

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,UniqueCarrier,AirlineID,Carrier,TailNum,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2017,3,9,25,1,2017-09-25,B6,20409,B6,N273JB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017,3,9,25,1,2017-09-25,B6,20409,B6,N198JB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017,3,9,25,1,2017-09-25,B6,20409,B6,N583JB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017,3,9,25,1,2017-09-25,B6,20409,B6,N665JB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017,3,9,25,1,2017-09-25,B6,20409,B6,N323JB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445822,2016,1,1,3,7,2016-01-03,F9,20436,F9,N934FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445823,2016,1,1,3,7,2016-01-03,F9,20436,F9,N934FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445824,2016,1,1,3,7,2016-01-03,F9,20436,F9,N935FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445825,2016,1,1,3,7,2016-01-03,F9,20436,F9,N935FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445826,2016,1,1,3,7,2016-01-03,F9,20436,F9,N935FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
os.chdir('D:\\programming\\practice\\Project\\Flight dataset')
#Droping all the columns that are not needed.
column_needed=[
'FlightDate',
'Quarter',
'Year',
'Month',
'DayofMonth',
'DepTime',
'DepDel15',
'CRSDepTime',
'DepDelayMinutes',
'OriginAirportID',
'DestAirportID',
'ArrTime',
'CRSArrTime',
'ArrDel15',
'Dest',
'Origin',
'ArrDelayMinutes',]
drop_column = [i for i in df1.columns if i not in column_needed]
drop_column
df1= df1.drop(drop_column,axis=1)

df1

In [ ]:
loclist = ["ATL",
"CLT",
"DEN",
"DFW",
'EWR',
"IAH",
"JFK",
"LAS",
"LAX",
"MCO",
"MIA",
"ORD",
"PHX",
"SEA",
"SFO",]

df1 = df1[df1['Origin'].isin(loclist) & df1['Dest'].isin(loclist)]
df1.to_csv('./combine2016-2017')

In [ ]:
df1 = pd.read_csv('./combine2016-2017')
df1 = df1.drop(['Unnamed: 0'],axis=1)
df1

In [ ]:
# os.chdir('D:\\programming\\practice\\Project\\Weather dataset\\weather\\ATL')
# with open(os.getcwd()+f'\\2016-3.json') as f:
#     temp = json.load(f)
#     final = pd.DataFrame()
#     for i in range(len(temp['data']['weather'])):
#         date = temp['data']['weather'][i]['date']
#         for j in range(len(temp['data']['weather'][i]['hourly'])):
#             each = pd.DataFrame.from_dict(temp['data']['weather'][i]['hourly'][j])
#             each['date'] = date
#             final = pd.concat([each,final])
#             final = final.drop(['FeelsLikeF','winddir16Point','FeelsLikeC','DewPointC','windspeedMiles','HeatIndexF','HeatIndexC','weatherIconUrl','WindGustMiles','WindChillC','tempC','weatherDesc'],axis=1)
#         print(final)

#loading the weather datasets
weather = pd.DataFrame()
os.chdir(cwd)
os.chdir(cwd+'//Weather dataset//weather')
print(os.getcwd())
wloop_init = os.getcwd()
for i in os.listdir():
    airport = i
    os.chdir(os.getcwd()+f'//{i}')
    print(i)
    for j in os.listdir():
        if ('2016'==j[0:4]) or ('2017'==j[0:4]):
            print(j)
            with open(os.getcwd()+f'\\{j}') as f:
                temp = json.load(f)
                final = pd.DataFrame()
                for days in range(len(temp['data']['weather'])):
                    date = temp['data']['weather'][days]['date']
                    for hrs in range(len(temp['data']['weather'][days]['hourly'])):
                        each = pd.DataFrame.from_dict(temp['data']['weather'][days]['hourly'][hrs])
                        each['date'] = date
                        each['airport'] = airport
                        final = pd.concat([each,final])
                        final = final.drop(['FeelsLikeF','winddir16Point','FeelsLikeC','DewPointC','windspeedMiles','HeatIndexF','HeatIndexC','weatherIconUrl','WindGustMiles','WindChillC','tempC','weatherDesc'],axis=1)
                weather = pd.concat([weather,final],axis=0) 
                

    os.chdir(wloop_init)

weather

In [ ]:
os.chdir('D:\\programming\\practice\\Project\\Weather dataset')
weather.to_csv('./weather_final')

In [ ]:
os.chdir('D:\\programming\\practice\\Project\\Weather dataset')
df2 = pd.read_csv('./weather_final')
df2 = df2.drop(['Unnamed: 0'],axis=1)
df2

In [6]:
df2['airport'].isnull().sum()

0